package com.jobportal.backend.model.enums;

public enum AuditAction {
    LOGIN,
    USER_REGISTERED,
    USER_UPDATED,
    JOB_CREATED,
    JOB_UPDATED,
    JOB_DELETED,
    APPLICATION_CREATED,
    APPLICATION_STATUS_CHANGED,
    RESUME_UPLOADED,
    RESUME_ANALYZED,
    INTERVIEW_SCHEDULED,
    INTERVIEW_STATUS_CHANGED,
    NOTIFICATION_CREATED
}
